spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    servlet.multipart.max-file-size: 5MB
    servlet.multipart.max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: local
    include: secret
